---
# ansible/playbook.yml
# This playbook runs the Logstash installation role on the "logstash_servers" server group.

- name: Install and configure Logstash
  hosts: logstash
  become: yes
  gather_facts: yes

  roles:
    - logstash_install

